name: Publish to PyPI

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write  # For trusted publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      uses: astral-sh/setup-uv-action@v0
      
    - name: Install build dependencies
      run: |
        uv pip install build
    
    - name: Build package
      run: |
        python -m build
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11